/* tslint:disable */
/* eslint-disable */
/**
 * Zero consult timesheet - OpenAPI 3.2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TimesheetEntry } from '../model';
/**
 * TimesheetApi - axios parameter creator
 */
export const TimesheetApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Add a new timesheet entry
         * @param {TimesheetEntry} timesheetEntry 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTimesheetEntry: async (timesheetEntry: TimesheetEntry, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'timesheetEntry' is not null or undefined
            assertParamExists('addTimesheetEntry', 'timesheetEntry', timesheetEntry)
            const localVarPath = `/timesheets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(timesheetEntry, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a timesheet entry
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimesheetEntry: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTimesheetEntry', 'id', id)
            const localVarPath = `/timesheets/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the list of timesheet entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        timesheetsList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/timesheets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a timesheet entry
         * @param {string} id 
         * @param {TimesheetEntry} timesheetEntry 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTimesheetEntry: async (id: string, timesheetEntry: TimesheetEntry, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTimesheetEntry', 'id', id)
            // verify required parameter 'timesheetEntry' is not null or undefined
            assertParamExists('updateTimesheetEntry', 'timesheetEntry', timesheetEntry)
            const localVarPath = `/timesheets/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(timesheetEntry, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TimesheetApi - functional programming interface
 */
export const TimesheetApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TimesheetApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Add a new timesheet entry
         * @param {TimesheetEntry} timesheetEntry 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addTimesheetEntry(timesheetEntry: TimesheetEntry, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimesheetEntry>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addTimesheetEntry(timesheetEntry, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TimesheetApi.addTimesheetEntry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a timesheet entry
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTimesheetEntry(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimesheetEntry>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTimesheetEntry(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TimesheetApi.getTimesheetEntry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the list of timesheet entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async timesheetsList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TimesheetEntry>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.timesheetsList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TimesheetApi.timesheetsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a timesheet entry
         * @param {string} id 
         * @param {TimesheetEntry} timesheetEntry 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTimesheetEntry(id: string, timesheetEntry: TimesheetEntry, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TimesheetEntry>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTimesheetEntry(id, timesheetEntry, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TimesheetApi.updateTimesheetEntry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TimesheetApi - factory interface
 */
export const TimesheetApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TimesheetApiFp(configuration)
    return {
        /**
         * 
         * @summary Add a new timesheet entry
         * @param {TimesheetEntry} timesheetEntry 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addTimesheetEntry(timesheetEntry: TimesheetEntry, options?: RawAxiosRequestConfig): AxiosPromise<TimesheetEntry> {
            return localVarFp.addTimesheetEntry(timesheetEntry, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a timesheet entry
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimesheetEntry(id: string, options?: RawAxiosRequestConfig): AxiosPromise<TimesheetEntry> {
            return localVarFp.getTimesheetEntry(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the list of timesheet entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        timesheetsList(options?: RawAxiosRequestConfig): AxiosPromise<Array<TimesheetEntry>> {
            return localVarFp.timesheetsList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a timesheet entry
         * @param {string} id 
         * @param {TimesheetEntry} timesheetEntry 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTimesheetEntry(id: string, timesheetEntry: TimesheetEntry, options?: RawAxiosRequestConfig): AxiosPromise<TimesheetEntry> {
            return localVarFp.updateTimesheetEntry(id, timesheetEntry, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TimesheetApi - object-oriented interface
 */
export class TimesheetApi extends BaseAPI {
    /**
     * 
     * @summary Add a new timesheet entry
     * @param {TimesheetEntry} timesheetEntry 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addTimesheetEntry(timesheetEntry: TimesheetEntry, options?: RawAxiosRequestConfig) {
        return TimesheetApiFp(this.configuration).addTimesheetEntry(timesheetEntry, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a timesheet entry
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTimesheetEntry(id: string, options?: RawAxiosRequestConfig) {
        return TimesheetApiFp(this.configuration).getTimesheetEntry(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the list of timesheet entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public timesheetsList(options?: RawAxiosRequestConfig) {
        return TimesheetApiFp(this.configuration).timesheetsList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a timesheet entry
     * @param {string} id 
     * @param {TimesheetEntry} timesheetEntry 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTimesheetEntry(id: string, timesheetEntry: TimesheetEntry, options?: RawAxiosRequestConfig) {
        return TimesheetApiFp(this.configuration).updateTimesheetEntry(id, timesheetEntry, options).then((request) => request(this.axios, this.basePath));
    }
}

