openapi: 3.1.0
info:
  title: Zero consult employee - OpenAPI 3.2
  description: ''
  version: 1.0.0
paths:
  /customers:
    get:
      tags:
        - customer
      summary: Get the list of customers
      operationId: customersList
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      tags:
        - customer
      summary: Add a new customer
      operationId: addCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /customers/{id}:
    delete:
      tags:
        - customer
      summary: Delete a customer
      operationId: deleteCustomer
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Customer deleted
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
        '405':
          description: 'Customer has timesheets so cannot be deleted'
          content:
            text/plain:
              schema:
                type: string
    get:
      tags:
        - customer
      summary: Get a customer
      operationId: getCustomer
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
    put:
      tags:
        - customer
      summary: Update a customer
      operationId: updateCustomer
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Customer updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
  /customers/{id}/hasTimesheetEntries:
    post:
      tags:
        - customer
      summary: mark customer hasTimesheetEntries
      operationId: updateCustomerHasTimesheetEntries
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hasTimesheetEntries:
                  type: boolean
              required:
                - hasTimesheetEntries
      responses:
        '200':
          description: Customer marked hasTimesheetEntries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /employees:
    get:
      tags:
        - employee
      summary: Get the list of employees
      operationId: employeesList
      responses:
        '200':
          description: A list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      tags:
        - employee
      summary: Add a new employee
      operationId: addEmployee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '201':
          description: Employee created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
  /employees/{id}:
    delete:
      tags:
        - employee
      summary: Delete an employee
      operationId: deleteEmployee
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Employee deleted
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
        '405':
          description: 'Employee has timesheets so cannot be deleted'
          content:
            text/plain:
              schema:
                type: string
    get:
      tags:
        - employee
      summary: Get an employee
      operationId: getEmployee
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Employee found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
    put:
      tags:
        - employee
      summary: Update an employee
      operationId: updateEmployee
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        '200':
          description: Employee updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
        '406':
          description: 'Circular manager reference'
          content:
            text/plain:
              schema:
                type: string
  /employees/{id}/hasTimesheetEntries:
    post:
      tags:
        - employee
      summary: mark employee hasTimesheetEntries
      operationId: updateEmployeeHasTimesheetEntries
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hasTimesheetEntries:
                  type: boolean
              required:
                - hasTimesheetEntries
      responses:
        '200':
          description: Employee marked hasTimesheetEntries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
  /user/login:
    post:
      tags:
        - user
      summary: login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInfo'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithToken'
        '403':
          description: Could not login
          content:
            text/plain:
              schema:
                type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Customer:
      type: object
      properties:
        city:
          type: string
        companyName:
          type: string
        contactPersonFirstName:
          type: string
        contactPersonLastName:
          type: string
        email:
          type: string
        hiringRatePerHour:
          type: number
          format: double
        hasTimesheetEntries:
          type: boolean
          readOnly: true
        id:
          type: string
        phone:
          type: string
        sector:
          $ref: '#/components/schemas/Sector'
        startDate:
          type: integer
          format: int64
        status:
          $ref: '#/components/schemas/CustomerStatus'
        website:
          type: string
      required:
        - companyName
        - contactPersonFirstName
        - contactPersonLastName
        - email
        - hiringRatePerHour
        - phone
        - startDate
        - sector
        - status
    CustomerStatus:
      type: string
      enum: [ "Active", "Inactive", "Prospect" ]
    Department:
      type: string
      enum: [ "Engineering", "Design", "Marketing", "HR", "Finance", "Operations" ]
    Employee:
      type: object
      properties:
        department:
          $ref: '#/components/schemas/Department'
        email:
          type: string
        firstName:
          type: string
        functionTitle:
          type: string
        grossWage:
          type: number
          format: double
        hasTimesheetEntries:
          type: boolean
          readOnly: true
        id:
          type: string
        lastName:
          type: string
        manager:
          $ref: '#/components/schemas/Employee'
        phone:
          type: string
        startDate:
          type: integer
          format: int64
        status:
          $ref: '#/components/schemas/EmployeeStatus'
      required:
        - email
        - firstName
        - lastName
        - grossWage
        - phone
        - startDate
        - status
    EmployeeStatus:
      type: string
      enum: [ "Active", "Inactive", "On leave" ]
    Sector:
      type: string
      enum: [ "Tech", "Retail", "Healthcare", "Finance", "Government", "Education", "Other"]
    LoginInfo:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    UserWithToken:
      type: object
      properties:
        token:
          type: string
        admin:
          type: boolean
        user:
          $ref: '#/components/schemas/Employee'
      required:
        - token
        - admin
        - user
security:
  - bearerAuth: [ ]