openapi: 3.1.0
info:
  title: Zero consult timesheet - OpenAPI 3.2
  description: ''
  version: 1.0.0
paths:
  /timesheets:
    get:
      tags:
        - timesheet
      summary: Get the list of timesheet entries
      operationId: timesheetsList
      parameters:
        - in: query
          name: from
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: until
          required: true
          schema:
            type: string
            format: date
        - in: query
          name: employeeId
          required: false
          schema:
            type: string
        - in: query
          name: customerId
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of timesheet entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimesheetEntry'
    post:
      tags:
        - timesheet
      summary: Add a new timesheet entry
      operationId: addTimesheetEntry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimesheetEntry'
      responses:
        '201':
          description: Timesheet entry created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesheetEntry'
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
        '406':
          description: 'Invoicing Month already closed'
          content:
            text/plain:
              schema:
                type: string
  /timesheets/{id}:
    delete:
      tags:
        - timesheet
      summary: Delete a timesheet entry
      operationId: deleteTimesheetEntry
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Timesheet entry deleted
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
        '406':
          description: 'Timesheet entry may not be in accepted state'
          content:
            text/plain:
              schema:
                type: string
    get:
      tags:
        - timesheet
      summary: Get a timesheet entry
      operationId: getTimesheetEntry
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Timesheet entry found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesheetEntry'
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
    put:
      tags:
        - timesheet
      summary: Update a timesheet entry
      operationId: updateTimesheetEntry
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimesheetEntry'
      responses:
        '200':
          description: Timesheet entry updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimesheetEntry'
        '404':
          description: 'Entity not found'
          content:
            text/plain:
              schema:
                type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TimesheetEntry:
      type: object
      properties:
        date:
          type: string
          format: date
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time
        employeeId:
          type: string
        customerId:
          type: string
        id:
          type: string
        createdAt:
          type: integer
          format: int64
        description:
          type: string
        status:
          $ref: '#/components/schemas/TimesheetStatus'
        type:
          $ref: '#/components/schemas/TimesheetType'
      required:
        - date
        - startTime
        - endTime
        - employeeId
        - status
        - type
    TimesheetStatus:
      type: string
      enum:
        - In progress
        - Approved
        - Rejected
    TimesheetType:
      type: string
      enum:
        - Work
        - Holiday
        - Sickness
security:
  - bearerAuth: [ ]